[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[dev]
command = "vite"
targetPort = 5173
port = 8888

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"

[[edge]]
path = "/*"
cache = "manual"
